# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - NSG

pool:
  vmImage: windows-latest

stages:
  - stage: Test
    jobs:
      - job: 'testNSG'
        steps:
          - task: RunARMTTKTests@1
            inputs:
              templatelocation: '$(System.DefaultWorkingDirectory)\NSG'
              resultLocation: '$(System.DefaultWorkingDirectory)\NSGtestResults'
              allTemplatesMain: true
          
          - task: PublishTestResults@2
            condition: always()
            inputs:
              testResultsFormat: 'NUnit'
              testResultsFiles: '$(System.DefaultWorkingDirectory)\NSGtestResults\*-armttk.xml'
              

  - stage: Deploy
    dependsOn: Test
    jobs:
      - job: "deployNSG"
        steps:
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: YOUR SC HERE
              ScriptType: 'InlineScript'
              Inline: 'New-AzResourceGroupDeployment -Name BicepNSGDeployment -ResourceGroupName rg_nsg_bicep -TemplateFile ".\NSG\main.bicep" -TemplateParameterFile ".\NSG\main.parameters.json"'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'